#!/usr/bin/env bash
# Configure nginx server

ADD301_RED="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
ADD404_NOT="\n\\terror_page 404 /404.html;\n\tlocation = /var/www/html/404.html {\n\t\tinternal;\n\t}"
PATTERN="#error_page 404 /404.html;"

sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.html
sudo sed -i "30i $ADD301_RED" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i "47i\ $PATTERN$ADD404_NOT" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
