#!/usr/bin/env bash
# configures a new server

apt-get -y update
apt-get -y install nginx

HOST=$(hostname)
HEADER="\\\n\tadd_header X-Served-By $HOST;\n"
FIND=$(grep "X-Server-by" /etc/nginx/sites-available/default)
if [[ -z $FIND ]]; then
	sed -i "23i $HEADER" /etc/nginx/sites-available/default
fi

echo "Hello World!" > /var/www/html/index.html

FIND=$(grep "redirect_me" /etc/nginx/sites-available/default)
STR="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=3MbaGJN2ioQ;\n\t}\n"
if [[ -z $FIND ]]; then
	sed -i "42i $STR" /etc/nginx/sites-available/default
fi

FIND=$(grep "error_page 404" /etc/nginx/sites-available/default)
ERR="\\\n\terror_page 404 /custom_404.html;\n"
if [[ -z $FIND ]]; then
	echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
	sed -i "40i $ERR" /etc/nginx/sites-available/default
fi

service nginx restart
