#!/usr/bin/env bash
# configures a loadbalancer HAproxy

apt-get -y update
apt-get -y install haproxy=1.6.\*

echo '
frontend RahilBux.tech
	bind 0:80
	default_backend web_servers

backend web_servers
	balance roundrobin
	server 424179-web-01 54.209.215.166
	server 424179-web-02 54.175.145.85
' >> /etc/haproxy/haproxy.cfg

service haproxy restart
