#!/usr/bin/env bash
# Prints numbers 1-100 and:
# if iteration is a multiple of 3 and 5: print FizzBuzz
# if iteration is a multiple of 3: print Fizz
# if iteration is a multiple of 5: print Buzz

for i in {1..100}
do
	if (( i % 15 == 0 ))
	then
		echo "FizzBuzz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	elif (( i % 3 == 0 ))
	then
		echo "Fizz"
	else
		echo "$i"
	fi
done
