#!/usr/bin/env bash
# File prints Best School 10 times and bad luck and good luch on the 4th and 8th iteration

i=1

while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
