#!/usr/bin/env bash
# Loops from 1-20 and:
# iteration 4 displays bad luck from China
# iteration 9 displays bad luck from Japan
# iteration 17 displays bad luck from Italy

i=1
while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	((i++))
done
