#!/usr/bin/env bash
# display a clock until 12hour 59minute

hour=0
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minute=1
	while [ $minute -le 59 ]
	do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
